version: '3.8'

services:
  db:
    image: postgres:15
    container_name: odoo16-db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo16_db_data:/var/lib/postgresql/data
    networks:
      - odoo16-net

  odoo:
    image: odoo:16
    container_name: odoo16
    restart: always
    user: "0:0"
    depends_on:
      - db
    command: "odoo --dev=reload --workers=0"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo16_web_data:/var/lib/odoo
      - /opt/odoo/odoo16/conf/odoo.conf:/etc/odoo/odoo.conf
      - /opt/odoo/odoo16/extra-addons:/mnt/extra-addons
      - /opt/odoo/odoo16/filestore:/root/.local/share/Odoo/filestore
    networks:
      - odoo16-net
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.odoo16.rule=Host(`odoo16.erpsoluciones.net`)"
      - "traefik.http.routers.odoo16.entrypoints=websecure"
      - "traefik.http.routers.odoo16.tls.certresolver=letsencrypt"
      - "traefik.http.services.odoo16.loadbalancer.server.port=8069"

volumes:
  odoo16_db_data:
  odoo16_web_data:

networks:
  odoo16-net:
    driver: bridge
  traefik:
    external: true
